# Generated by Django 4.2.23 on 2025-09-25 00:10

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningUnitFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remote_raster', models.URLField(blank=True, help_text='URL to a remote raster layer for this planning unit family. Leave blank to use local vector layer.', null=True)),
            ],
            options={
                'verbose_name': 'Planning Unit Family',
                'verbose_name_plural': 'Planning Unit Families',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('text', 'Text'), ('number', 'Number')], help_text='Type of the question.', max_length=50)),
                ('is_required', models.BooleanField(default=False, help_text='Check if this question is required.')),
                ('collect_other', models.BooleanField(default=False, help_text="Check if an 'Other' option should be provided for multiple choice questions.")),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('value', models.IntegerField(help_text='Numeric value associated with this option.')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
            },
        ),
        migrations.CreateModel(
            name='QuestionSurveyAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of the question in the survey.')),
                ('question', models.ForeignKey(help_text='The question associated with the survey.', on_delete=django.db.models.deletion.CASCADE, related_name='survey_associations', to='survey.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('user_defined_pus', models.BooleanField(default=False, help_text='Check if this survey uses user drawings rather than pre-defined planning units.')),
                ('study_bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Define the study area for this survey.', null=True, srid=4326)),
                ('selection_snapping', models.CharField(choices=[('default', 'Default'), ('intersects', 'Intersection'), ('is_within', 'Is Within')], help_text='Select the snapping behavior for planning unit selection.', max_length=50)),
                ('is_spatial', models.BooleanField(default=True, help_text='Check if user will enter spatial data.')),
                ('is_weighted', models.BooleanField(default=True, help_text='Check if user will assign coins to answers.')),
                ('total_coins', models.IntegerField(default=100, help_text='Total number of coins available to users for weighting selections.')),
                ('require_all_coins_used', models.BooleanField(default=True, help_text='Check if users must use all coins when weighting selections.')),
                ('min_coins_per_pu', models.IntegerField(default=1, help_text='Minimum number of coins that must be assigned to each planning unit.')),
                ('max_coins_per_pu', models.IntegerField(default=100, help_text='Maximum number of coins that can be assigned to each planning unit.')),
                ('groups', models.ManyToManyField(blank=True, help_text='Select groups that can access this survey.', related_name='surveys', to='auth.group')),
                ('pu_family', models.ForeignKey(blank=True, help_text='Select the Planning Unit Family this survey belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='survey.planningunitfamily')),
                ('questions', models.ManyToManyField(blank=True, help_text='Select questions to include in this survey.', related_name='surveys', through='survey.QuestionSurveyAssociation', to='survey.question')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
            },
        ),
        migrations.AddField(
            model_name='questionsurveyassociation',
            name='survey',
            field=models.ForeignKey(help_text='The survey this question is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='question_associations', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, help_text='Options for multiple choice or single choice questions.', related_name='questions', to='survey.questionoption'),
        ),
        migrations.CreateModel(
            name='PlanningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Geometry of the planning unit.', null=True, srid=4326)),
                ('family', models.ManyToManyField(help_text='Select the Planning Unit Families this planning unit belongs to.', related_name='planning_units', to='survey.planningunitfamily')),
            ],
            options={
                'verbose_name': 'Planning Unit',
                'verbose_name_plural': 'Planning Units',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(help_text='The survey this response belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey')),
                ('user', models.ForeignKey(help_text='The user who submitted this response.', on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'unique_together': {('survey', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='questionsurveyassociation',
            unique_together={('question', 'survey')},
        ),
    ]
