# Generated by Django 4.2.23 on 2025-10-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0027_alter_theme_data_source_alter_theme_source'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyLayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Order of the layer group in the survey.')),
                ('survey', models.ForeignKey(help_text='The survey this layer group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='survey_layer_groups_survey', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Survey Layer Group',
                'verbose_name_plural': 'Survey Layer Groups',
            },
        ),
        migrations.CreateModel(
            name='SurveyLayerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_show', models.BooleanField(default=False, help_text='Check if this layer should be shown by default when the survey is loaded.')),
                ('order', models.PositiveIntegerField(help_text='Order of the layer in the group.')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_layer_orders_layer', to='layers.layer')),
                ('layer_group', models.ForeignKey(help_text='The survey layer group this layer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='survey_layer_orders_layer_group', to='survey.surveylayergroup')),
            ],
            options={
                'verbose_name': 'Survey Layer Order',
                'verbose_name_plural': 'Survey Layer Orders',
                'unique_together': {('layer', 'layer_group')},
            },
        ),
    ]
