# Generated by Django 4.2.23 on 2025-11-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveylayergroup_surveylayerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='selection_snapping',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('intersects', 'Intersection'), ('is_within', 'Is Within')], default='default', help_text='Select the snapping behavior for planning unit selection.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='allow_multiple_responses',
            field=models.BooleanField(default=False, help_text='[NOT YET IMPLEMENTED!]: Check if users can submit multiple responses to this survey.'),
        ),
    ]
